(set -e
# shCryptoAesWithGithubOrg npmdoc /bin/sh "$HOME/src/sandbox2/.task.sh"
# shCryptoAesWithGithubOrg kaizhu256 shTravisTaskPush "$HOME/src/sandbox2/.task.sh"
# shCryptoAesWithGithubOrg kaizhu256 shGithubRepoListTouch npmdoc/node-npmdoc-npm '[npm publishAfterCommitAfterBuild]'
# [$ /bin/sh .task.sh]

cd /tmp
if [ "$TRAVIS" ]
then
    npm install "kaizhu256/node-utility2#alpha"
    . ./node_modules/.bin/utility2
    eval "$(shTravisCryptoAesDecryptYml $CRYPTO_AES_KEY_npmdoc npmdoc)"
fi
. ./node_modules/.bin/utility2
export PATH="/tmp/node_modules/.bin:$PATH"
export npm_config_dir_utility2="/tmp/node_modules/utility2"
shInit

#!! [ '01.02.01 cron',
  #!! '2017.02.19 uglifyjs-lite',
  #!! '2017.02.20 swgg',
  #!! '2017.02.27 jslint-lite',
  #!! '2017.02.28 istanbul-lite',
  #!! '2017.03.07 electron-lite',
  #!! '2017.03.16 apidoc-lite',
  #!! '2017.03.16 db-lite',
  #!! '2017.03.19 swagger-ui-lite',
  #!! '2017.03.21 utility2' ]

#!! II=2450
#!! while [ "$II" -lt 3000 ]
#!! do
    #!! LIST="https://www.npmjs.com/browse/star?offset=$II"
    #!! printf "$LIST\n"
    #!! LIST="$(shNpmNameListGetFromUrl "$LIST")"
    #!! LIST2=""
    #!! for NAME in $LIST
    #!! do
        #!! NAME="$(shNpmNameNormalize $NAME)"
        #!! if [ "$NAME" ]
        #!! then
            #!! LIST2="$LIST2
#!! npmdoc/node-npmdoc-$NAME"
        #!! fi
    #!! done
    #!! LIST="$LIST2"
    #!! printf "$LIST\n"
    #!! shGithubRepoListCreate "$LIST" npmdoc
    #!! II="$((II+32))"
#!! done

#!! II=850
#!! while [ "$II" -lt 1000 ]
#!! II=1000
#!! while [ "$II" -lt 1001 ]
#!! do
    #!! LIST="https://www.npmjs.com/browse/star?offset=$II"
    #!! printf "$LIST\n"
    #!! #!! export TRAVIS_REPO_CREATE_FORCE=1
    #!! shNpmdocRepoListCreate "$LIST"
    #!! II="$((II+32))"
#!! done

LIST="
npmdoc/node-npmdoc-co-request
npmdoc/node-npmdoc-couchbase
npmdoc/node-npmdoc-country-data
npmdoc/node-npmdoc-countryjs
npmdoc/node-npmdoc-coverify
npmdoc/node-npmdoc-co-views
npmdoc/node-npmdoc-cpr
npmdoc/node-npmdoc-cpx
npmdoc/node-npmdoc-cradle
npmdoc/node-npmdoc-crapify
npmdoc/node-npmdoc-credential
npmdoc/node-npmdoc-crontab
npmdoc/node-npmdoc-cryptiles
npmdoc/node-npmdoc-crypto-browserify
npmdoc/node-npmdoc-cson
npmdoc/node-npmdoc-csrf
npmdoc/node-npmdoc-csscomb
npmdoc/node-npmdoc-css-element-queries
npmdoc/node-npmdoc-cssmin
npmdoc/node-npmdoc-cssnext
npmdoc/node-npmdoc-cssom
npmdoc/node-npmdoc-css-parse
npmdoc/node-npmdoc-css-purge
npmdoc/node-npmdoc-cssshrink
npmdoc/node-npmdoc-csvjson
npmdoc/node-npmdoc-csv-parse
npmdoc/node-npmdoc-csv-streamify
npmdoc/node-npmdoc-csv-write-stream
npmdoc/node-npmdoc-curry
npmdoc/node-npmdoc-cz-conventional-changelog
npmdoc/node-npmdoc-daemon
npmdoc/node-npmdoc-dat
npmdoc/node-npmdoc-datapumps
npmdoc/node-npmdoc-datatables
npmdoc/node-npmdoc-datauri
npmdoc/node-npmdoc-date-fns
npmdoc/node-npmdoc-date-format
npmdoc/node-npmdoc-dav
npmdoc/node-npmdoc-db-migrate
npmdoc/node-npmdoc-ddos
npmdoc/node-npmdoc-ddp
npmdoc/node-npmdoc-deasync
npmdoc/node-npmdoc-debounce
npmdoc/node-npmdoc-debowerify
npmdoc/node-npmdoc-decimal.js
npmdoc/node-npmdoc-decompress
npmdoc/node-npmdoc-decompress-zip
npmdoc/node-npmdoc-deep-extend
npmdoc/node-npmdoc-deep-freeze
npmdoc/node-npmdoc-deepmerge
npmdoc/node-npmdoc-delegates
npmdoc/node-npmdoc-deployd
npmdoc/node-npmdoc-derby
npmdoc/node-npmdoc-detective
npmdoc/node-npmdoc-devtool
npmdoc/node-npmdoc-dexie
npmdoc/node-npmdoc-dezalgo
npmdoc/node-npmdoc-diacritics
npmdoc/node-npmdoc-digitalocean
npmdoc/node-npmdoc-directory-tree
npmdoc/node-npmdoc-disc
npmdoc/node-npmdoc-diskdb
npmdoc/node-npmdoc-diskusage
npmdoc/node-npmdoc-dispatchr
npmdoc/node-npmdoc-dmx
npmdoc/node-npmdoc-doctoc
npmdoc/node-npmdoc-documentation
npmdoc/node-npmdoc-doiuse
npmdoc/node-npmdoc-dominos
npmdoc/node-npmdoc-domready
npmdoc/node-npmdoc-dot
npmdoc/node-npmdoc-dot-prop
npmdoc/node-npmdoc-downpress
npmdoc/node-npmdoc-downsize
npmdoc/node-npmdoc-dox
npmdoc/node-npmdoc-draft-js
npmdoc/node-npmdoc-dragula
npmdoc/node-npmdoc-drakov
npmdoc/node-npmdoc-dredd
npmdoc/node-npmdoc-dropbox
npmdoc/node-npmdoc-duo
npmdoc/node-npmdoc-duplexer
npmdoc/node-npmdoc-duplexify
npmdoc/node-npmdoc-dustjs-linkedin
npmdoc/node-npmdoc-dynamics.js
npmdoc/node-npmdoc-each-async
npmdoc/node-npmdoc-eases
npmdoc/node-npmdoc-easy-table
npmdoc/node-npmdoc-edit-google-spreadsheet
npmdoc/node-npmdoc-ejs-mate
npmdoc/node-npmdoc-elasticdump
npmdoc/node-npmdoc-electrolyte
npmdoc/node-npmdoc-electron-connect
npmdoc/node-npmdoc-electron-json-storage
npmdoc/node-npmdoc-electron-pdf
npmdoc/node-npmdoc-electron-reload
npmdoc/node-npmdoc-email
npmdoc/node-npmdoc-ember-api-actions
npmdoc/node-npmdoc-ember-bootstrap
npmdoc/node-npmdoc-ember-can
npmdoc/node-npmdoc-ember-cli-admin
npmdoc/node-npmdoc-ember-cli-async-button
npmdoc/node-npmdoc-ember-cli-chart
npmdoc/node-npmdoc-ember-cli-deploy
npmdoc/node-npmdoc-ember-cli-document-title
npmdoc/node-npmdoc-ember-cli-dotenv
npmdoc/node-npmdoc-ember-cli-font-awesome
npmdoc/node-npmdoc-ember-cli-gravatar
npmdoc/node-npmdoc-ember-cli-materialize
npmdoc/node-npmdoc-ember-cli-simple-auth-token
npmdoc/node-npmdoc-ember-feature-flags
npmdoc/node-npmdoc-emberfire
npmdoc/node-npmdoc-ember-infinity
npmdoc/node-npmdoc-ember-local-storage
npmdoc/node-npmdoc-ember-modal-dialog
npmdoc/node-npmdoc-ember-notify
npmdoc/node-npmdoc-ember-responsive
npmdoc/node-npmdoc-ember-simple-auth
npmdoc/node-npmdoc-ember-truth-helpers
npmdoc/node-npmdoc-ember-websockets
npmdoc/node-npmdoc-encoding
npmdoc/node-npmdoc-end-of-stream
npmdoc/node-npmdoc-entities
npmdoc/node-npmdoc-enum
npmdoc/node-npmdoc-enumify
npmdoc/node-npmdoc-error
npmdoc/node-npmdoc-errors
npmdoc/node-npmdoc-es5-shim
npmdoc/node-npmdoc-es6-module-loader
npmdoc/node-npmdoc-es6-promisify
npmdoc/node-npmdoc-es6-shim
npmdoc/node-npmdoc-escape-string-regexp
npmdoc/node-npmdoc-esformatter
npmdoc/node-npmdoc-eslint-config-standard
npmdoc/node-npmdoc-eslint-friendly-formatter
npmdoc/node-npmdoc-eslint-plugin-babel
npmdoc/node-npmdoc-eslint-plugin-filenames
npmdoc/node-npmdoc-eslint-plugin-html
npmdoc/node-npmdoc-eslint-plugin-jsx-a11y
npmdoc/node-npmdoc-eslint-plugin-promise
npmdoc/node-npmdoc-eslint-watch
npmdoc/node-npmdoc-etag
npmdoc/node-npmdoc-eventemitter3
npmdoc/node-npmdoc-eventsource
npmdoc/node-npmdoc-excel-parser
npmdoc/node-npmdoc-exec
npmdoc/node-npmdoc-exec-sync
npmdoc/node-npmdoc-exif
npmdoc/node-npmdoc-exit
npmdoc/node-npmdoc-exorcist
npmdoc/node-npmdoc-expect.js
npmdoc/node-npmdoc-express-bunyan-logger
npmdoc/node-npmdoc-express-debug
npmdoc/node-npmdoc-express-device
npmdoc/node-npmdoc-express-ejs-layouts
npmdoc/node-npmdoc-express-error-handler
npmdoc/node-npmdoc-express-favicon
npmdoc/node-npmdoc-express-fileupload
npmdoc/node-npmdoc-express-flash
npmdoc/node-npmdoc-express.io
npmdoc/node-npmdoc-express-ipfilter
npmdoc/node-npmdoc-express-logger
npmdoc/node-npmdoc-express-minify
npmdoc/node-npmdoc-express-mongoose-generator
npmdoc/node-npmdoc-express-mysql-session
npmdoc/node-npmdoc-express-react-views
npmdoc/node-npmdoc-express-resource
npmdoc/node-npmdoc-express-sanitizer
npmdoc/node-npmdoc-express-socket.io-session
npmdoc/node-npmdoc-express-status-monitor
npmdoc/node-npmdoc-express-useragent
npmdoc/node-npmdoc-express-ws
npmdoc/node-npmdoc-express-xml-bodyparser
npmdoc/node-npmdoc-eyes
npmdoc/node-npmdoc-fabric
npmdoc/node-npmdoc-facebook-chat-api
npmdoc/node-npmdoc-facebook-node-sdk
npmdoc/node-npmdoc-faced
npmdoc/node-npmdoc-falafel
npmdoc/node-npmdoc-falcor
npmdoc/node-npmdoc-famous
npmdoc/node-npmdoc-fantasy-land
npmdoc/node-npmdoc-fast
npmdoc/node-npmdoc-fast-json-patch
npmdoc/node-npmdoc-favicons-webpack-plugin
npmdoc/node-npmdoc-faye-websocket
npmdoc/node-npmdoc-fb-watchman
npmdoc/node-npmdoc-feed-read
npmdoc/node-npmdoc-ffi
npmdoc/node-npmdoc-ffmpeg
npmdoc/node-npmdoc-figures
npmdoc/node-npmdoc-file
npmdoc/node-npmdoc-file-stream-rotator
npmdoc/node-npmdoc-finalhandler
npmdoc/node-npmdoc-find
npmdoc/node-npmdoc-findit
npmdoc/node-npmdoc-findup-sync
npmdoc/node-npmdoc-firebase-tools
npmdoc/node-npmdoc-fis
npmdoc/node-npmdoc-five
npmdoc/node-npmdoc-flatiron
npmdoc/node-npmdoc-flickrapi
npmdoc/node-npmdoc-fly
npmdoc/node-npmdoc-font-awesome-webpack
npmdoc/node-npmdoc-forecast
npmdoc/node-npmdoc-forever-service
npmdoc/node-npmdoc-forms
npmdoc/node-npmdoc-form-serialize
npmdoc/node-npmdoc-formsy-react
npmdoc/node-npmdoc-foundation
npmdoc/node-npmdoc-foundation-sites
npmdoc/node-npmdoc-fresh
npmdoc/node-npmdoc-frisby
npmdoc/node-npmdoc-fs-jetpack
npmdoc/node-npmdoc-fstream
npmdoc/node-npmdoc-ftpd
npmdoc/node-npmdoc-ftps
npmdoc/node-npmdoc-fuck-you
npmdoc/node-npmdoc-fuse.js
npmdoc/node-npmdoc-gauge
npmdoc/node-npmdoc-generator-ionic
npmdoc/node-npmdoc-generator-node-webkit
npmdoc/node-npmdoc-generator-polymer
npmdoc/node-npmdoc-generator-react-fullstack
npmdoc/node-npmdoc-generator-webapp
npmdoc/node-npmdoc-generator-zf5
npmdoc/node-npmdoc-geocoder
npmdoc/node-npmdoc-geojson
npmdoc/node-npmdoc-get-env
npmdoc/node-npmdoc-get-port
npmdoc/node-npmdoc-gh
npmdoc/node-npmdoc-gh-pages-deploy
npmdoc/node-npmdoc-gitgoodies
npmdoc/node-npmdoc-github-webhook-handler
npmdoc/node-npmdoc-git-release-notes
npmdoc/node-npmdoc-git-rev
npmdoc/node-npmdoc-git-server
npmdoc/node-npmdoc-git-tools
npmdoc/node-npmdoc-gl-matrix
npmdoc/node-npmdoc-global
npmdoc/node-npmdoc-glob-stream
npmdoc/node-npmdoc-google-auth-library
npmdoc/node-npmdoc-google-calendar
npmdoc/node-npmdoc-google-cdn
npmdoc/node-npmdoc-google-closure-compiler-js
npmdoc/node-npmdoc-google-drive
npmdoc/node-npmdoc-google-libphonenumber
npmdoc/node-npmdoc-google-locations
npmdoc/node-npmdoc-googlemaps
npmdoc/node-npmdoc-google-translate
npmdoc/node-npmdoc-google-trends-api
npmdoc/node-npmdoc-gpio
npmdoc/node-npmdoc-gramophone
npmdoc/node-npmdoc-gray-matter
npmdoc/node-npmdoc-gremlins.js
npmdoc/node-npmdoc-gridfs-stream
npmdoc/node-npmdoc-growl
npmdoc/node-npmdoc-grunt-babel
npmdoc/node-npmdoc-grunt-bower
npmdoc/node-npmdoc-grunt-bower-concat
npmdoc/node-npmdoc-grunt-bowercopy
npmdoc/node-npmdoc-grunt-bower-install-simple
npmdoc/node-npmdoc-grunt-bower-requirejs
npmdoc/node-npmdoc-grunt-combine-media-queries
npmdoc/node-npmdoc-grunt-contrib
npmdoc/node-npmdoc-grunt-contrib-coffee
npmdoc/node-npmdoc-grunt-contrib-jade
npmdoc/node-npmdoc-grunt-contrib-livereload
npmdoc/node-npmdoc-grunt-contrib-rename
npmdoc/node-npmdoc-grunt-contrib-stylus
npmdoc/node-npmdoc-grunt-csscomb
npmdoc/node-npmdoc-grunt-env
npmdoc/node-npmdoc-grunt-exec
npmdoc/node-npmdoc-grunt-filerev
npmdoc/node-npmdoc-grunt-ftp-deploy
npmdoc/node-npmdoc-grunt-githooks
npmdoc/node-npmdoc-grunt-grunticon
npmdoc/node-npmdoc-grunt-html2js
npmdoc/node-npmdoc-grunt-html-validation
npmdoc/node-npmdoc-grunt-image
npmdoc/node-npmdoc-grunt-image-resize
npmdoc/node-npmdoc-grunt-include-replace
npmdoc/node-npmdoc-grunt-jsbeautifier
npmdoc/node-npmdoc-grunt-jscs
npmdoc/node-npmdoc-grunt-mocha-istanbul
npmdoc/node-npmdoc-grunt-mocha-test
npmdoc/node-npmdoc-grunt-ngmin
npmdoc/node-npmdoc-grunt-node-inspector
npmdoc/node-npmdoc-grunt-node-webkit-builder
npmdoc/node-npmdoc-grunt-open
npmdoc/node-npmdoc-grunt-phantomas
npmdoc/node-npmdoc-grunt-postcss
npmdoc/node-npmdoc-grunt-preprocess
npmdoc/node-npmdoc-grunt-prompt
npmdoc/node-npmdoc-grunt-responsive-images
npmdoc/node-npmdoc-grunt-rev
npmdoc/node-npmdoc-grunt-rsync
npmdoc/node-npmdoc-grunt-sftp-deploy
npmdoc/node-npmdoc-grunt-ssh
npmdoc/node-npmdoc-grunt-string-replace
npmdoc/node-npmdoc-grunt-svgmin
npmdoc/node-npmdoc-grunt-sync
npmdoc/node-npmdoc-grunt-typescript
npmdoc/node-npmdoc-grunt-webpack
npmdoc/node-npmdoc-grunt-wordpress-deploy
npmdoc/node-npmdoc-grunt-wp-i18n
npmdoc/node-npmdoc-guid
npmdoc/node-npmdoc-gulp-angular-htmlify
npmdoc/node-npmdoc-gulp-batch
npmdoc/node-npmdoc-gulp-beautify
npmdoc/node-npmdoc-gulp-bless
npmdoc/node-npmdoc-gulp-bundle-assets
npmdoc/node-npmdoc-gulp-buster
npmdoc/node-npmdoc-gulp-cache-bust
npmdoc/node-npmdoc-gulp-cdnizer
npmdoc/node-npmdoc-gulp-change
npmdoc/node-npmdoc-gulp-check-unused-css
npmdoc/node-npmdoc-gulp-closure-compiler
npmdoc/node-npmdoc-gulp-coffeelint
npmdoc/node-npmdoc-gulp-consolidate
npmdoc/node-npmdoc-gulp-convert
npmdoc/node-npmdoc-gulp-coverage
npmdoc/node-npmdoc-gulp-cssbeautify
npmdoc/node-npmdoc-gulp-cssimport
npmdoc/node-npmdoc-gulp-css-spriter
npmdoc/node-npmdoc-gulp-declare
npmdoc/node-npmdoc-gulp-download
npmdoc/node-npmdoc-gulp-ejs
npmdoc/node-npmdoc-gulp-electron
npmdoc/node-npmdoc-gulp-email-builder
npmdoc/node-npmdoc-gulp-environments
npmdoc/node-npmdoc-gulp-favicons
npmdoc/node-npmdoc-gulp-front-matter
npmdoc/node-npmdoc-gulp-group-css-media-queries
npmdoc/node-npmdoc-gulp-hash
npmdoc/node-npmdoc-gulp-htmlbuild
npmdoc/node-npmdoc-gulp-html-extend
npmdoc/node-npmdoc-gulp-htmlhint
npmdoc/node-npmdoc-gulp-html-prettify
npmdoc/node-npmdoc-gulp-html-tag-include
npmdoc/node-npmdoc-gulp-iconify
npmdoc/node-npmdoc-gulp-if-else
npmdoc/node-npmdoc-gulp-image
npmdoc/node-npmdoc-gulp-inject-string
npmdoc/node-npmdoc-gulp-inline
npmdoc/node-npmdoc-gulp-insert
npmdoc/node-npmdoc-gulp-jsbeautifier
npmdoc/node-npmdoc-gulp-jslint
npmdoc/node-npmdoc-gulp-json-editor
npmdoc/node-npmdoc-gulp-jsonlint
npmdoc/node-npmdoc-gulp-jsonminify
npmdoc/node-npmdoc-gulp-karma
npmdoc/node-npmdoc-gulp-live-server
npmdoc/node-npmdoc-gulp-main-bower-files
npmdoc/node-npmdoc-gulp-mocha-phantomjs
npmdoc/node-npmdoc-gulp-ng-config
npmdoc/node-npmdoc-gulp-ngdocs
npmdoc/node-npmdoc-gulp-ng-html2js
npmdoc/node-npmdoc-gulp-obfuscate
npmdoc/node-npmdoc-gulp-pixrem
npmdoc/node-npmdoc-gulp-plato
npmdoc/node-npmdoc-gulp-prettify
npmdoc/node-npmdoc-gulp-print
npmdoc/node-npmdoc-gulp-processhtml
npmdoc/node-npmdoc-gulp-protractor
npmdoc/node-npmdoc-gulp-real-favicon
npmdoc/node-npmdoc-gulp-regex-replace
npmdoc/node-npmdoc-gulp-replace-task
npmdoc/node-npmdoc-gulp-responsive
npmdoc/node-npmdoc-gulp-rev-append
npmdoc/node-npmdoc-gulp-rev-css-url
npmdoc/node-npmdoc-gulp-s3
npmdoc/node-npmdoc-gulp-sass-glob
npmdoc/node-npmdoc-gulp-sitemap
npmdoc/node-npmdoc-gulp-spritesmith
npmdoc/node-npmdoc-gulp-standard
npmdoc/node-npmdoc-gulp-streamify
npmdoc/node-npmdoc-gulp-strip-comments
npmdoc/node-npmdoc-gulp-svg2png
npmdoc/node-npmdoc-gulp-symlink
npmdoc/node-npmdoc-gulp-sync
npmdoc/node-npmdoc-gulp-tag-version
npmdoc/node-npmdoc-gulp-task-listing
npmdoc/node-npmdoc-gulp-task-loader
npmdoc/node-npmdoc-gulp-template
npmdoc/node-npmdoc-gulp-tinypng-compress
npmdoc/node-npmdoc-gulp-todo
npmdoc/node-npmdoc-gulp-tslint
npmdoc/node-npmdoc-gulp-uglifyjs
npmdoc/node-npmdoc-gulp-vulcanize
npmdoc/node-npmdoc-gulp-w3cjs
npmdoc/node-npmdoc-gulp-webp
npmdoc/node-npmdoc-gulp-wrap
npmdoc/node-npmdoc-guvnor
npmdoc/node-npmdoc-gzip-size
npmdoc/node-npmdoc-hackmyresume
npmdoc/node-npmdoc-handlebars-helpers
npmdoc/node-npmdoc-handlebars-layouts
npmdoc/node-npmdoc-hapi-auth-jwt2
npmdoc/node-npmdoc-hapi-authorization
npmdoc/node-npmdoc-hapi-react-views
npmdoc/node-npmdoc-hapi-swagger
npmdoc/node-npmdoc-happypack
npmdoc/node-npmdoc-harp
npmdoc/node-npmdoc-has
npmdoc/node-npmdoc-hasha
npmdoc/node-npmdoc-hashmap
npmdoc/node-npmdoc-hashmark
npmdoc/node-npmdoc-hat
npmdoc/node-npmdoc-haxe
npmdoc/node-npmdoc-hbsfy
npmdoc/node-npmdoc-highlight
npmdoc/node-npmdoc-highlights
npmdoc/node-npmdoc-hogan-express
npmdoc/node-npmdoc-hogan.js
npmdoc/node-npmdoc-homebridge-http
npmdoc/node-npmdoc-homebridge-mqtt
npmdoc/node-npmdoc-homebridge-platform-wemo
npmdoc/node-npmdoc-homebridge-server
npmdoc/node-npmdoc-homebridge-sonos
npmdoc/node-npmdoc-hoodie
npmdoc/node-npmdoc-hooker
npmdoc/node-npmdoc-hook.io
npmdoc/node-npmdoc-horizon
npmdoc/node-npmdoc-hotel
npmdoc/node-npmdoc-howler
npmdoc/node-npmdoc-hpp
npmdoc/node-npmdoc-html
npmdoc/node-npmdoc-html2jade
npmdoc/node-npmdoc-html5shiv
npmdoc/node-npmdoc-html5-to-pdf
npmdoc/node-npmdoc-html-loader
npmdoc/node-npmdoc-html-snapshots
npmdoc/node-npmdoc-html-to-pdf
npmdoc/node-npmdoc-httpdispatcher
npmdoc/node-npmdoc-http-framework
npmdoc/node-npmdoc-http-master
npmdoc/node-npmdoc-httpp-proxy
npmdoc/node-npmdoc-http-status
npmdoc/node-npmdoc-http-status-codes
npmdoc/node-npmdoc-hubot-jenkins
npmdoc/node-npmdoc-humanize
npmdoc/node-npmdoc-humps
npmdoc/node-npmdoc-huntsman
npmdoc/node-npmdoc-hyperglue
npmdoc/node-npmdoc-hyperline
npmdoc/node-npmdoc-hyperquest
npmdoc/node-npmdoc-hyperscript
npmdoc/node-npmdoc-hyperterm-paste
npmdoc/node-npmdoc-hyperx
npmdoc/node-npmdoc-i
npmdoc/node-npmdoc-i18n-2
npmdoc/node-npmdoc-ical
npmdoc/node-npmdoc-ignore
npmdoc/node-npmdoc-imagemagick-native
npmdoc/node-npmdoc-imagemin-svgo
npmdoc/node-npmdoc-image-resizer
npmdoc/node-npmdoc-images
npmdoc/node-npmdoc-image-to-ascii
npmdoc/node-npmdoc-image-type
npmdoc/node-npmdoc-image-webpack-loader
npmdoc/node-npmdoc-imap-simple
npmdoc/node-npmdoc-imdb-api
npmdoc/node-npmdoc-inert
npmdoc/node-npmdoc-inflection
npmdoc/node-npmdoc-influx
npmdoc/node-npmdoc-ink-docstrap
npmdoc/node-npmdoc-inline-css
npmdoc/node-npmdoc-insert-css
npmdoc/node-npmdoc-instagram
npmdoc/node-npmdoc-instagram-api
npmdoc/node-npmdoc-intern
npmdoc/node-npmdoc-intl
npmdoc/node-npmdoc-invariant
npmdoc/node-npmdoc-in-view
npmdoc/node-npmdoc-ionic-angular
npmdoc/node-npmdoc-ionic-framework
npmdoc/node-npmdoc-ionicons
npmdoc/node-npmdoc-ionic-plugin-keyboard
npmdoc/node-npmdoc-ios-deploy
npmdoc/node-npmdoc-ipify
npmdoc/node-npmdoc-ipp
npmdoc/node-npmdoc-ipware
npmdoc/node-npmdoc-iron
npmdoc/node-npmdoc-iron-node
npmdoc/node-npmdoc-is_js
npmdoc/node-npmdoc-is-my-json-valid
npmdoc/node-npmdoc-isparta
npmdoc/node-npmdoc-j
npmdoc/node-npmdoc-jake
npmdoc/node-npmdoc-jasmine-core
npmdoc/node-npmdoc-javascripting
npmdoc/node-npmdoc-javascript-state-machine
npmdoc/node-npmdoc-jeet
npmdoc/node-npmdoc-jenkins
npmdoc/node-npmdoc-jenkins-api
npmdoc/node-npmdoc-jest
npmdoc/node-npmdoc-jison
npmdoc/node-npmdoc-jquery.cookie
npmdoc/node-npmdoc-jquery-file-upload-middleware
npmdoc/node-npmdoc-jquery.inputmask
npmdoc/node-npmdoc-js2coffee
npmdoc/node-npmdoc-jsbarcode
npmdoc/node-npmdoc-js-base64
npmdoc/node-npmdoc-jsbn
npmdoc/node-npmdoc-jscpd
npmdoc/node-npmdoc-js-csp
npmdoc/node-npmdoc-jsforce
npmdoc/node-npmdoc-jsftp
npmdoc/node-npmdoc-js-git
npmdoc/node-npmdoc-jsinspect
npmdoc/node-npmdoc-json2xls
npmdoc/node-npmdoc-json5
npmdoc/node-npmdoc-json-api
npmdoc/node-npmdoc-jsoneditor
npmdoc/node-npmdoc-jsonld
npmdoc/node-npmdoc-jsonlint
npmdoc/node-npmdoc-json-loader
npmdoc/node-npmdoc-json-mask
npmdoc/node-npmdoc-jsonp
npmdoc/node-npmdoc-jsonparse
npmdoc/node-npmdoc-jsonpath
npmdoc/node-npmdoc-json-rpc2
npmdoc/node-npmdoc-json-schema
npmdoc/node-npmdoc-json-schema-faker
npmdoc/node-npmdoc-json-select
npmdoc/node-npmdoc-json-sql
npmdoc/node-npmdoc-jsontool
npmdoc/node-npmdoc-json-web-token
npmdoc/node-npmdoc-jsx-control-statements
npmdoc/node-npmdoc-jugglingdb
npmdoc/node-npmdoc-juice
npmdoc/node-npmdoc-juice2
npmdoc/node-npmdoc-jwt-decode
npmdoc/node-npmdoc-karma-browserify
npmdoc/node-npmdoc-karma-chai
npmdoc/node-npmdoc-karma-chrome-launcher
npmdoc/node-npmdoc-karma-cli
npmdoc/node-npmdoc-karma-mocha-reporter
npmdoc/node-npmdoc-karma-nyan-reporter
npmdoc/node-npmdoc-karma-spec-reporter
npmdoc/node-npmdoc-katex
npmdoc/node-npmdoc-kerberos
npmdoc/node-npmdoc-keygrip
npmdoc/node-npmdoc-keytar
npmdoc/node-npmdoc-keyword-extractor
npmdoc/node-npmdoc-koa-bodyparser
npmdoc/node-npmdoc-koa-compose
npmdoc/node-npmdoc-koa-cors
npmdoc/node-npmdoc-koa-logger
npmdoc/node-npmdoc-koa-middlewares
npmdoc/node-npmdoc-koa-route
npmdoc/node-npmdoc-koa-send
npmdoc/node-npmdoc-koa-session
npmdoc/node-npmdoc-koa-validate
npmdoc/node-npmdoc-lastfmapi
npmdoc/node-npmdoc-lazy
npmdoc/node-npmdoc-lazy.js
npmdoc/node-npmdoc-less-middleware
npmdoc/node-npmdoc-less-plugin-autoprefix
npmdoc/node-npmdoc-leveldown
npmdoc/node-npmdoc-levelgraph
npmdoc/node-npmdoc-level-js
npmdoc/node-npmdoc-level-sublevel
npmdoc/node-npmdoc-leven
npmdoc/node-npmdoc-levenshtein
npmdoc/node-npmdoc-licensing
npmdoc/node-npmdoc-likely
npmdoc/node-npmdoc-limdu
npmdoc/node-npmdoc-listr
npmdoc/node-npmdoc-live-reload
npmdoc/node-npmdoc-lmd
npmdoc/node-npmdoc-local-links
npmdoc/node-npmdoc-local-npm
npmdoc/node-npmdoc-lodash-cli
npmdoc/node-npmdoc-lodash-deep
npmdoc/node-npmdoc-lodash-node
npmdoc/node-npmdoc-logfmt
npmdoc/node-npmdoc-loggly
npmdoc/node-npmdoc-long
npmdoc/node-npmdoc-longjohn
npmdoc/node-npmdoc-lost
npmdoc/node-npmdoc-lunr
npmdoc/node-npmdoc-lynx
npmdoc/node-npmdoc-machine_learning
npmdoc/node-npmdoc-madge
npmdoc/node-npmdoc-magnific-popup
npmdoc/node-npmdoc-maildev
npmdoc/node-npmdoc-mailgen
npmdoc/node-npmdoc-mailgun
npmdoc/node-npmdoc-mailin
npmdoc/node-npmdoc-mail-listener2
npmdoc/node-npmdoc-main-loop
npmdoc/node-npmdoc-mandrill-api
npmdoc/node-npmdoc-map-stream
npmdoc/node-npmdoc-mariasql
npmdoc/node-npmdoc-markdown-to-html
npmdoc/node-npmdoc-marked-terminal
npmdoc/node-npmdoc-masonry-layout
npmdoc/node-npmdoc-massive
npmdoc/node-npmdoc-matcha
npmdoc/node-npmdoc-matchdep
npmdoc/node-npmdoc-material-design-lite
npmdoc/node-npmdoc-materialize-css
npmdoc/node-npmdoc-maxmind
npmdoc/node-npmdoc-md5-file
npmdoc/node-npmdoc-mean-cli
npmdoc/node-npmdoc-meanio
npmdoc/node-npmdoc-medium-editor
npmdoc/node-npmdoc-memdb-server
npmdoc/node-npmdoc-memory-fs
npmdoc/node-npmdoc-menubar
npmdoc/node-npmdoc-mercury
npmdoc/node-npmdoc-merge2
npmdoc/node-npmdoc-merge-descriptors
npmdoc/node-npmdoc-methods
npmdoc/node-npmdoc-micromatch
npmdoc/node-npmdoc-midi
npmdoc/node-npmdoc-migrate
npmdoc/node-npmdoc-minify
npmdoc/node-npmdoc-minifyify
npmdoc/node-npmdoc-minty
npmdoc/node-npmdoc-mississippi
npmdoc/node-npmdoc-mocha-phantomjs
npmdoc/node-npmdoc-mochawesome
npmdoc/node-npmdoc-mochify
npmdoc/node-npmdoc-mockjs
npmdoc/node-npmdoc-model
npmdoc/node-npmdoc-module-deps
npmdoc/node-npmdoc-moment-range
npmdoc/node-npmdoc-mongoosastic
npmdoc/node-npmdoc-mongoose-deep-populate
npmdoc/node-npmdoc-mongoose-delete
npmdoc/node-npmdoc-mongoose-timestamp
npmdoc/node-npmdoc-mongoose-unique-validator
npmdoc/node-npmdoc-mori
npmdoc/node-npmdoc-mout
npmdoc/node-npmdoc-moviedb
npmdoc/node-npmdoc-msee
npmdoc/node-npmdoc-msexcel-builder
npmdoc/node-npmdoc-msgpack
npmdoc/node-npmdoc-msgpack5
npmdoc/node-npmdoc-msgpack-lite
npmdoc/node-npmdoc-msnodesql
npmdoc/node-npmdoc-multer-s3
npmdoc/node-npmdoc-multilevel
npmdoc/node-npmdoc-multiline
npmdoc/node-npmdoc-multipipe
npmdoc/node-npmdoc-musicmetadata
npmdoc/node-npmdoc-must
npmdoc/node-npmdoc-mysql2
npmdoc/node-npmdoc-mysql-activerecord
npmdoc/node-npmdoc-napa
npmdoc/node-npmdoc-nar
npmdoc/node-npmdoc-native-dns
npmdoc/node-npmdoc-nativescript-cardview
npmdoc/node-npmdoc-nativescript-push-notifications
npmdoc/node-npmdoc-nativescript-telerik-ui
npmdoc/node-npmdoc-natural-brain
npmdoc/node-npmdoc-neo4j
npmdoc/node-npmdoc-net-ping
npmdoc/node-npmdoc-nets
npmdoc/node-npmdoc-net-snmp
npmdoc/node-npmdoc-network
npmdoc/node-npmdoc-network-address
npmdoc/node-npmdoc-ng2-toastr
npmdoc/node-npmdoc-ng-annotate
npmdoc/node-npmdoc-ng-annotate-webpack-plugin
npmdoc/node-npmdoc-ngeohash
npmdoc/node-npmdoc-ng-file-upload
npmdoc/node-npmdoc-niceware
npmdoc/node-npmdoc-nlp_compromise
npmdoc/node-npmdoc-node-base64-image
npmdoc/node-npmdoc-nodebot-workshop
npmdoc/node-npmdoc-node-bourbon
npmdoc/node-npmdoc-node-cmd
npmdoc/node-npmdoc-node-core-audio
npmdoc/node-npmdoc-node-curl
npmdoc/node-npmdoc-node-dir
npmdoc/node-npmdoc-node-emoji
npmdoc/node-npmdoc-node-env-file
npmdoc/node-npmdoc-node-etcd
npmdoc/node-npmdoc-node-expat
npmdoc/node-npmdoc-node.extend
npmdoc/node-npmdoc-node-google-apps-script
npmdoc/node-npmdoc-node-gyp-install
npmdoc/node-npmdoc-node-hue-api
npmdoc/node-npmdoc-node-ipc
npmdoc/node-npmdoc-nodejieba
npmdoc/node-npmdoc-node-json-db
npmdoc/node-npmdoc-nodejs-websocket
npmdoc/node-npmdoc-node-jsx
npmdoc/node-npmdoc-node-linkedin
npmdoc/node-npmdoc-nodemailer-smtp-transport
npmdoc/node-npmdoc-node-mandrill
npmdoc/node-npmdoc-node-minify
npmdoc/node-npmdoc-node-mocks-http
npmdoc/node-npmdoc-node-mysql
npmdoc/node-npmdoc-node-neo4j
npmdoc/node-npmdoc-node-odata
npmdoc/node-npmdoc-node-opcua
npmdoc/node-npmdoc-nodepdf
npmdoc/node-npmdoc-node-persist
npmdoc/node-npmdoc-node-phantom
npmdoc/node-npmdoc-node-php
npmdoc/node-npmdoc-node-pre-gyp
npmdoc/node-npmdoc-node-progress-bars
npmdoc/node-npmdoc-node-python
npmdoc/node-npmdoc-node-readability
npmdoc/node-npmdoc-node-repl
npmdoc/node-npmdoc-node-resque
npmdoc/node-npmdoc-node-scrapy
npmdoc/node-npmdoc-node-summary
npmdoc/node-npmdoc-node-svm
npmdoc/node-npmdoc-node-telegram-bot
npmdoc/node-npmdoc-node-telegram-bot-api
npmdoc/node-npmdoc-node-trello
npmdoc/node-npmdoc-node-tweet-stream
npmdoc/node-npmdoc-node-twitterbot
npmdoc/node-npmdoc-node-uglifier
npmdoc/node-npmdoc-nodeunit
npmdoc/node-npmdoc-node-webcl
npmdoc/node-npmdoc-node-webkit-updater
npmdoc/node-npmdoc-node-wit
npmdoc/node-npmdoc-node-zookeeper-client
npmdoc/node-npmdoc-noflo
npmdoc/node-npmdoc-nools
npmdoc/node-npmdoc-normalize-scss
npmdoc/node-npmdoc-np
npmdoc/node-npmdoc-nplaym
npmdoc/node-npmdoc-npm2dot
npmdoc/node-npmdoc-npm-cache
npmdoc/node-npmdoc-npm-collection-staff-picks
npmdoc/node-npmdoc-npmd
npmdoc/node-npmdoc-npm-expansions
npmdoc/node-npmdoc-npm-gui
npmdoc/node-npmdoc-npm-install-missing
npmdoc/node-npmdoc-npm_lazy
npmdoc/node-npmdoc-npmlog
npmdoc/node-npmdoc-npm-stats
npmdoc/node-npmdoc-npm-watch
npmdoc/node-npmdoc-npm-windows-upgrade
npmdoc/node-npmdoc-nsqjs
npmdoc/node-npmdoc-ntl
npmdoc/node-npmdoc-numbers
npmdoc/node-npmdoc-nw
npmdoc/node-npmdoc-oauth2orize
npmdoc/node-npmdoc-object-hash
npmdoc/node-npmdoc-object-sizeof
npmdoc/node-npmdoc-oboe
npmdoc/node-npmdoc-observed
npmdoc/node-npmdoc-officegen
npmdoc/node-npmdoc-ogr2ogr
npmdoc/node-npmdoc-only
npmdoc/node-npmdoc-openpgp
npmdoc/node-npmdoc-openssl-wrapper
npmdoc/node-npmdoc-osa
npmdoc/node-npmdoc-os-homedir
npmdoc/node-npmdoc-osmosis
npmdoc/node-npmdoc-owasp-password-strength-test
npmdoc/node-npmdoc-p5
npmdoc/node-npmdoc-package
npmdoc/node-npmdoc-papaparse
npmdoc/node-npmdoc-paper
npmdoc/node-npmdoc-paralleljs
npmdoc/node-npmdoc-parcelify
npmdoc/node-npmdoc-parker
npmdoc/node-npmdoc-parse5
npmdoc/node-npmdoc-parse-react
npmdoc/node-npmdoc-parse-server
npmdoc/node-npmdoc-parse-torrent
npmdoc/node-npmdoc-parseurl
npmdoc/node-npmdoc-partialify
npmdoc/node-npmdoc-particles.js
npmdoc/node-npmdoc-partition-bundle
npmdoc/node-npmdoc-passport-github
npmdoc/node-npmdoc-passport-http-bearer
npmdoc/node-npmdoc-passport-local-mongoose
npmdoc/node-npmdoc-passport-oauth
npmdoc/node-npmdoc-passport-oauth2
npmdoc/node-npmdoc-passport-windowsauth
npmdoc/node-npmdoc-password-hash
npmdoc/node-npmdoc-path-is-absolute
npmdoc/node-npmdoc-patrun
npmdoc/node-npmdoc-paypal-rest-sdk
npmdoc/node-npmdoc-pcap
npmdoc/node-npmdoc-pdf2json
npmdoc/node-npmdoc-pdf-extract
npmdoc/node-npmdoc-pdf-image
npmdoc/node-npmdoc-pdfjs-dist
npmdoc/node-npmdoc-pdfmake
npmdoc/node-npmdoc-peerflix
npmdoc/node-npmdoc-peerjs
npmdoc/node-npmdoc-peer-vnc
npmdoc/node-npmdoc-pegjs
npmdoc/node-npmdoc-perfjankie
npmdoc/node-npmdoc-performance-now
npmdoc/node-npmdoc-phantomas
npmdoc/node-npmdoc-phantomcss
npmdoc/node-npmdoc-phantomjs2
npmdoc/node-npmdoc-phaser
npmdoc/node-npmdoc-phone
npmdoc/node-npmdoc-phonegap-plugin-barcodescanner
npmdoc/node-npmdoc-phonegap-plugin-contentsync
npmdoc/node-npmdoc-phonegap-plugin-push
npmdoc/node-npmdoc-photoswipe
npmdoc/node-npmdoc-phpjs
npmdoc/node-npmdoc-picturefill
npmdoc/node-npmdoc-pino
npmdoc/node-npmdoc-pixl-xml
npmdoc/node-npmdoc-pkgcloud
npmdoc/node-npmdoc-pkginfo
npmdoc/node-npmdoc-player
npmdoc/node-npmdoc-playmusic
npmdoc/node-npmdoc-plist
npmdoc/node-npmdoc-pmx
npmdoc/node-npmdoc-polymer-cli
npmdoc/node-npmdoc-pomelo
npmdoc/node-npmdoc-portfinder
npmdoc/node-npmdoc-portscanner
npmdoc/node-npmdoc-pos
npmdoc/node-npmdoc-postal
npmdoc/node-npmdoc-postcss-font-magician
npmdoc/node-npmdoc-postcss-import
npmdoc/node-npmdoc-power-assert
npmdoc/node-npmdoc-precommit-hook
npmdoc/node-npmdoc-precss
npmdoc/node-npmdoc-preprocess
npmdoc/node-npmdoc-prettydiff
npmdoc/node-npmdoc-pretty-hrtime
npmdoc/node-npmdoc-printer
npmdoc/node-npmdoc-process
npmdoc/node-npmdoc-progress-stream
npmdoc/node-npmdoc-promised-mongo
npmdoc/node-npmdoc-protocol-buffers
npmdoc/node-npmdoc-protractor-html-screenshot-reporter
npmdoc/node-npmdoc-proxy-middleware
npmdoc/node-npmdoc-p-s
npmdoc/node-npmdoc-psd
npmdoc/node-npmdoc-ps-node
npmdoc/node-npmdoc-ps-tree
npmdoc/node-npmdoc-pubnub
npmdoc/node-npmdoc-punycode
npmdoc/node-npmdoc-purdy
npmdoc/node-npmdoc-purify-css
npmdoc/node-npmdoc-pushbullet
npmdoc/node-npmdoc-push.js
npmdoc/node-npmdoc-pushover
npmdoc/node-npmdoc-pushover-notifications
npmdoc/node-npmdoc-pushstate-server
npmdoc/node-npmdoc-python
npmdoc/node-npmdoc-qrcode-terminal
npmdoc/node-npmdoc-queue
npmdoc/node-npmdoc-qwery
npmdoc/node-npmdoc-raccoon
npmdoc/node-npmdoc-radium
npmdoc/node-npmdoc-raf
npmdoc/node-npmdoc-randomatic
npmdoc/node-npmdoc-randomstring
npmdoc/node-npmdoc-random-string
npmdoc/node-npmdoc-rand-token
npmdoc/node-npmdoc-raspicam
npmdoc/node-npmdoc-raw-body
npmdoc/node-npmdoc-rbac2
npmdoc/node-npmdoc-react-addons-pure-render-mixin
npmdoc/node-npmdoc-react-addons-update
npmdoc/node-npmdoc-react-autosuggest
npmdoc/node-npmdoc-react-css-modules
npmdoc/node-npmdoc-react-dates
npmdoc/node-npmdoc-react-dnd
npmdoc/node-npmdoc-react-draggable
npmdoc/node-npmdoc-react-fontawesome
npmdoc/node-npmdoc-react-google-maps
npmdoc/node-npmdoc-react-icons
npmdoc/node-npmdoc-react-image-gallery
npmdoc/node-npmdoc-react-immutable-proptypes
npmdoc/node-npmdoc-react-masonry-component
npmdoc/node-npmdoc-react-mdl
npmdoc/node-npmdoc-react-modal
npmdoc/node-npmdoc-react-monocle
npmdoc/node-npmdoc-react-native-animatable
npmdoc/node-npmdoc-react-native-blur
npmdoc/node-npmdoc-react-native-camera
npmdoc/node-npmdoc-react-native-css
npmdoc/node-npmdoc-react-native-device
npmdoc/node-npmdoc-react-native-fs
npmdoc/node-npmdoc-react-native-image-picker
npmdoc/node-npmdoc-react-native-push-notification
npmdoc/node-npmdoc-react-native-scrollable-tab-view
npmdoc/node-npmdoc-react-native-sqlite-storage
npmdoc/node-npmdoc-react-native-vector-icons
npmdoc/node-npmdoc-react-notification
npmdoc/node-npmdoc-react-responsive
npmdoc/node-npmdoc-react-server-example
npmdoc/node-npmdoc-react-sketchapp
npmdoc/node-npmdoc-react-sparklines
npmdoc/node-npmdoc-react-sticky
npmdoc/node-npmdoc-react-toolbox
npmdoc/node-npmdoc-react-tooltip
npmdoc/node-npmdoc-react-ui-builder
npmdoc/node-npmdoc-react-virtualized
npmdoc/node-npmdoc-react-waypoint
npmdoc/node-npmdoc-read
npmdoc/node-npmdoc-readdirp
npmdoc/node-npmdoc-readline
npmdoc/node-npmdoc-readline-sync
npmdoc/node-npmdoc-read-package-json
npmdoc/node-npmdoc-realm
npmdoc/node-npmdoc-re-base
npmdoc/node-npmdoc-redis-commander
npmdoc/node-npmdoc-redux-actions
npmdoc/node-npmdoc-redux-api-middleware
npmdoc/node-npmdoc-redux-logger
npmdoc/node-npmdoc-redux-mock-store
npmdoc/node-npmdoc-redux-persist
npmdoc/node-npmdoc-redux-promise-middleware
npmdoc/node-npmdoc-redux-react-router
npmdoc/node-npmdoc-regenerator
npmdoc/node-npmdoc-reginabox
npmdoc/node-npmdoc-remarkable
npmdoc/node-npmdoc-renamer
npmdoc/node-npmdoc-replace
npmdoc/node-npmdoc-replacestream
npmdoc/node-npmdoc-replify
npmdoc/node-npmdoc-requestify
npmdoc/node-npmdoc-request-progress
npmdoc/node-npmdoc-require-all
npmdoc/node-npmdoc-response-time
npmdoc/node-npmdoc-restangular
npmdoc/node-npmdoc-restify-oauth2
npmdoc/node-npmdoc-restling
npmdoc/node-npmdoc-resume-cli
npmdoc/node-npmdoc-retext
npmdoc/node-npmdoc-rethinkdbdash
npmdoc/node-npmdoc-retire
npmdoc/node-npmdoc-rework
npmdoc/node-npmdoc-rollbar
npmdoc/node-npmdoc-rootpath
npmdoc/node-npmdoc-router
npmdoc/node-npmdoc-rsmq
npmdoc/node-npmdoc-rss-watcher
npmdoc/node-npmdoc-rtail
npmdoc/node-npmdoc-run-parallel
npmdoc/node-npmdoc-rupture
npmdoc/node-npmdoc-safe-regex
npmdoc/node-npmdoc-sails-auth
npmdoc/node-npmdoc-sails-permissions
npmdoc/node-npmdoc-sane
npmdoc/node-npmdoc-sanitize.css
npmdoc/node-npmdoc-sanitize-filename
npmdoc/node-npmdoc-sass
npmdoc/node-npmdoc-sass-lint
npmdoc/node-npmdoc-satelize
npmdoc/node-npmdoc-say
npmdoc/node-npmdoc-sbd
npmdoc/node-npmdoc-sc5-styleguide
npmdoc/node-npmdoc-schema-inspector
npmdoc/node-npmdoc-scissors
npmdoc/node-npmdoc-scp2
npmdoc/node-npmdoc-screenshot-stream
npmdoc/node-npmdoc-scrollmagic
npmdoc/node-npmdoc-scrypt
npmdoc/node-npmdoc-scuttlebutt
npmdoc/node-npmdoc-seaport
npmdoc/node-npmdoc-search-index
npmdoc/node-npmdoc-select2
npmdoc/node-npmdoc-selectize
npmdoc/node-npmdoc-send
npmdoc/node-npmdoc-serialize-javascript
npmdoc/node-npmdoc-seriate
npmdoc/node-npmdoc-serve-index
npmdoc/node-npmdoc-serverless
npmdoc/node-npmdoc-servicebus
npmdoc/node-npmdoc-session.socket.io
npmdoc/node-npmdoc-sha1
npmdoc/node-npmdoc-shader-school
npmdoc/node-npmdoc-shave
npmdoc/node-npmdoc-shelljs-nodecli
npmdoc/node-npmdoc-shell-task
npmdoc/node-npmdoc-shipit
npmdoc/node-npmdoc-shipit-cli
npmdoc/node-npmdoc-shoe
npmdoc/node-npmdoc-shopify-node-api
npmdoc/node-npmdoc-short
npmdoc/node-npmdoc-siege
npmdoc/node-npmdoc-sigmund
npmdoc/node-npmdoc-silly-datetime
npmdoc/node-npmdoc-simplecrawler
npmdoc/node-npmdoc-simple-oauth2
npmdoc/node-npmdoc-simple-peer
npmdoc/node-npmdoc-simple-ssh
npmdoc/node-npmdoc-simple-statistics
npmdoc/node-npmdoc-single-line-log
npmdoc/node-npmdoc-skrollr
npmdoc/node-npmdoc-slash
npmdoc/node-npmdoc-sleep
npmdoc/node-npmdoc-sliced
npmdoc/node-npmdoc-slick-carousel
npmdoc/node-npmdoc-slugify
npmdoc/node-npmdoc-smartcrop
npmdoc/node-npmdoc-smart-grid
npmdoc/node-npmdoc-smtp-connection
npmdoc/node-npmdoc-smtp-protocol
npmdoc/node-npmdoc-snapsvg
npmdoc/node-npmdoc-snazzy
npmdoc/node-npmdoc-social-login
npmdoc/node-npmdoc-socketcluster
npmdoc/node-npmdoc-socketio-jwt
npmdoc/node-npmdoc-socketstream
npmdoc/node-npmdoc-solr-client
npmdoc/node-npmdoc-sortablejs
npmdoc/node-npmdoc-sourced
npmdoc/node-npmdoc-sparkly
npmdoc/node-npmdoc-speakeasy
npmdoc/node-npmdoc-speakeasy-nlp
npmdoc/node-npmdoc-speakingurl
npmdoc/node-npmdoc-speed-test
npmdoc/node-npmdoc-speedtest-net
npmdoc/node-npmdoc-spm
npmdoc/node-npmdoc-spotify-web-api-node
npmdoc/node-npmdoc-sprintf
npmdoc/node-npmdoc-sql-cli
npmdoc/node-npmdoc-sql.js
npmdoc/node-npmdoc-sse
npmdoc/node-npmdoc-stack-trace
npmdoc/node-npmdoc-stackvis
npmdoc/node-npmdoc-stampit
npmdoc/node-npmdoc-stanford-simple-nlp
npmdoc/node-npmdoc-static-favicon
npmdoc/node-npmdoc-stats-webpack-plugin
npmdoc/node-npmdoc-stdio
npmdoc/node-npmdoc-steam
npmdoc/node-npmdoc-sticky-session
npmdoc/node-npmdoc-stream-combiner
npmdoc/node-npmdoc-streamqueue
npmdoc/node-npmdoc-stream-spigot
npmdoc/node-npmdoc-stream-splicer
npmdoc/node-npmdoc-stringify
npmdoc/node-npmdoc-string-similarity
npmdoc/node-npmdoc-string-template
npmdoc/node-npmdoc-stylestats
npmdoc/node-npmdoc-stylint
npmdoc/node-npmdoc-stylus-loader
npmdoc/node-npmdoc-subdomain
npmdoc/node-npmdoc-suncalc
npmdoc/node-npmdoc-superagent-promise
npmdoc/node-npmdoc-superb
npmdoc/node-npmdoc-superstatic
npmdoc/node-npmdoc-surge
npmdoc/node-npmdoc-susy
npmdoc/node-npmdoc-svg2ttf
npmdoc/node-npmdoc-svg-sprite
npmdoc/node-npmdoc-swarm
npmdoc/node-npmdoc-sweetalert
npmdoc/node-npmdoc-sweet.js
npmdoc/node-npmdoc-swiper
npmdoc/node-npmdoc-synaptic
npmdoc/node-npmdoc-sync
npmdoc/node-npmdoc-sync-request
npmdoc/node-npmdoc-tabletojson
npmdoc/node-npmdoc-tail
npmdoc/node-npmdoc-tap-spec
npmdoc/node-npmdoc-tar.gz
npmdoc/node-npmdoc-tar-stream
npmdoc/node-npmdoc-tcp-ping
npmdoc/node-npmdoc-temp
npmdoc/node-npmdoc-templar
npmdoc/node-npmdoc-temporal
npmdoc/node-npmdoc-terminal-kit
npmdoc/node-npmdoc-tesseract.js
npmdoc/node-npmdoc-thenify
npmdoc/node-npmdoc-thepiratebay
npmdoc/node-npmdoc-thinkjs
npmdoc/node-npmdoc-thinky
npmdoc/node-npmdoc-three.js
npmdoc/node-npmdoc-throng
npmdoc/node-npmdoc-tildify
npmdoc/node-npmdoc-timeseries-analysis
npmdoc/node-npmdoc-tinderbot
npmdoc/node-npmdoc-toastr
npmdoc/node-npmdoc-toobusy-js
npmdoc/node-npmdoc-topojson
npmdoc/node-npmdoc-torrent
npmdoc/node-npmdoc-torrent-stream
npmdoc/node-npmdoc-tracer
npmdoc/node-npmdoc-trails
npmdoc/node-npmdoc-trello
npmdoc/node-npmdoc-tsify
npmdoc/node-npmdoc-ttf2woff
npmdoc/node-npmdoc-tunnel-ssh
npmdoc/node-npmdoc-turf
npmdoc/node-npmdoc-twemoji
npmdoc/node-npmdoc-twilio
npmdoc/node-npmdoc-twitter-stream-channels
npmdoc/node-npmdoc-typeahead.js
npmdoc/node-npmdoc-type-check
npmdoc/node-npmdoc-type-is
npmdoc/node-npmdoc-uglify
npmdoc/node-npmdoc-uglifycss
npmdoc/node-npmdoc-uid-safe
npmdoc/node-npmdoc-unfluff
npmdoc/node-npmdoc-unidecode
npmdoc/node-npmdoc-union
npmdoc/node-npmdoc-uniq
npmdoc/node-npmdoc-up
npmdoc/node-npmdoc-updtr
npmdoc/node-npmdoc-upstarter
npmdoc/node-npmdoc-urijs
npmdoc/node-npmdoc-url-join
npmdoc/node-npmdoc-urllib
npmdoc/node-npmdoc-url-pattern
npmdoc/node-npmdoc-ursa
npmdoc/node-npmdoc-usage
npmdoc/node-npmdoc-usb-detection
npmdoc/node-npmdoc-utils-merge
npmdoc/node-npmdoc-validate
npmdoc/node-npmdoc-validate.js
npmdoc/node-npmdoc-validatorjs
npmdoc/node-npmdoc-valid-url
npmdoc/node-npmdoc-vinyl-ftp
npmdoc/node-npmdoc-vinyl-map
npmdoc/node-npmdoc-vinyl-transform
npmdoc/node-npmdoc-vision
npmdoc/node-npmdoc-vk-io
npmdoc/node-npmdoc-vogels
npmdoc/node-npmdoc-voxel-engine
npmdoc/node-npmdoc-vtop
npmdoc/node-npmdoc-vue-cli
npmdoc/node-npmdoc-vue-loader
npmdoc/node-npmdoc-vue-router
npmdoc/node-npmdoc-walk
npmdoc/node-npmdoc-walkdir
npmdoc/node-npmdoc-warning
npmdoc/node-npmdoc-wavi
npmdoc/node-npmdoc-waypoints
npmdoc/node-npmdoc-weak
npmdoc/node-npmdoc-webcomponents.js
npmdoc/node-npmdoc-webdriver-manager
npmdoc/node-npmdoc-webfontloader
npmdoc/node-npmdoc-webpack-dev-middleware
npmdoc/node-npmdoc-webpack-isomorphic-tools
npmdoc/node-npmdoc-webpack-load-plugins
npmdoc/node-npmdoc-webpack-manifest-plugin
npmdoc/node-npmdoc-webpack-notifier
npmdoc/node-npmdoc-webpack-visualizer-plugin
npmdoc/node-npmdoc-web-push
npmdoc/node-npmdoc-website-scraper
npmdoc/node-npmdoc-web-terminal
npmdoc/node-npmdoc-wechat-api
npmdoc/node-npmdoc-wechat-oauth
npmdoc/node-npmdoc-which
npmdoc/node-npmdoc-wifi-password
npmdoc/node-npmdoc-windows-build-tools
npmdoc/node-npmdoc-windows-cpu
npmdoc/node-npmdoc-winston-daily-rotate-file
npmdoc/node-npmdoc-winston-mongodb
npmdoc/node-npmdoc-wkhtmltopdf
npmdoc/node-npmdoc-wordpress
npmdoc/node-npmdoc-wordwrap
npmdoc/node-npmdoc-worker-farm
npmdoc/node-npmdoc-workshopper
npmdoc/node-npmdoc-world-countries
npmdoc/node-npmdoc-wpapi
npmdoc/node-npmdoc-wrtc
npmdoc/node-npmdoc-wzrd
npmdoc/node-npmdoc--xlsjs
npmdoc/node-npmdoc-xls-to-json
npmdoc/node-npmdoc-xlsx-to-json
npmdoc/node-npmdoc-xmlbuilder
npmdoc/node-npmdoc-xmlhttprequest
npmdoc/node-npmdoc-xml-js
npmdoc/node-npmdoc-xml-writer
npmdoc/node-npmdoc-xss
npmdoc/node-npmdoc-xss-filters
npmdoc/node-npmdoc-yaml
npmdoc/node-npmdoc-yar
npmdoc/node-npmdoc-yauzl
npmdoc/node-npmdoc-youtube-node
npmdoc/node-npmdoc-yo-yo
npmdoc/node-npmdoc-yui
npmdoc/node-npmdoc-zerorpc
npmdoc/node-npmdoc-zone.js
npmdoc/node-npmdoc-zookeeper
npmdoc/node-npmdoc-zxcvbn
"

shListUnflattenAndApplyFunction() {(set -e
    LIST="$1"
    #!! export TRAVIS_REPO_CREATE_FORCE=1
    shNpmdocRepoListCreate "$LIST"
    #!! shGithubRepoListTouch "$LIST" '[npm publishAfterCommitAfterBuild]'
    #!! shGithubRepoListCreate "$LIST" npmdoc
)}
shListUnflattenAndApply "$LIST" 16

)
